settings:
  name: Google Cloud Storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Google Cloud Storage docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: View your Google Cloud Storage buckets
          url: /task-viewing-gcp-storage.html
    - title: Manage Google Cloud Storage buckets
      entries:
        - title: Add new buckets
          url: /task-add-gcp-bucket.html
        - title: Change bucket settings
          url: /task-change-gcp-bucket-settings.html
        - title: Use NetApp data services with Google Cloud Storage buckets
          url: /task-gcp-enable-data-services.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Storage Management
  repo: storage-management-family
