---
sidebar: sidebar
permalink: task-add-gcp-bucket.html
keywords: google cloud storage buckets, google cloud storage, add buckets
summary: When your Google Cloud Storage system is available in the Systems page, you can add additional buckets directly from the NetApp Console.
---

= Add Google Cloud Storage buckets
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When your Google Cloud Storage system is available in the Systems page, you can add additional buckets directly from the NetApp Console.

.Steps

. From the Systems page, double-click the Google Cloud Storage system to view the Google Cloud Storage buckets Overview page, and click *Add bucket*.
+
The _Add bucket_ page is displayed.

. Enter the required information in the _Project details_ section.
* *Bucket name* - Enter the name you want to use for the bucket. https://cloud.google.com/storage/docs/buckets#naming[See the Google Cloud documentation for naming requirements^].
* *Google project* - Select the Google project that will be the owner of the bucket. This can be the primary project where the Console agent was deployed, or it can be a different project.
If you don't see any additional projects in the drop-down list, then you haven't associated the NetApp Console service account with other projects yet. Go to the Google Cloud console, open the IAM service, and select the project. Add the service account with the NetApp Console role to that project. You'll need to repeat this step for each project.
NOTE: This is the service account that you set up for the NetApp Console, https://docs.netapp.com/us-en/console-setup-admin/task-set-up-permissions-google.html#set-up-permissions-for-the-connector[as described on this page^].
* *Labels* - Labels are metadata for your Google Cloud resources. You can add up to 10 label key:value pairs when creating a bucket. 
https://cloud.google.com/compute/docs/labeling-resources[See the Google Cloud documentation for more information about labels^].

. In the _Location_ section, select the location type and region (or regions) where the bucket will be created. You can select from three different types of locations.
+
[cols=2*,options="header",cols="35,65"]
|===
| If you select the "Location type"...
| Then select...

| Region | A single region from the "Available regions" field.

| Dual-region a| The geographic location (a single continent) from the "Available locations" field, and then select two regions in the "Available regions" field. 

You can enable "Turbo replication" if you want to guarantee geo-redundancy for all newly written objects within a target of 15 minutes.

| Multi-region | The geographic multi-region from the "Available multi-regions" field. 

|=== 
+
Note that all Cloud Storage data is redundant across at least two zones within at least one geographic place as soon as you upload it. https://cloud.google.com/storage/docs/locations[See the Google Cloud documentation for more information about bucket locations^].

. In the _Storage class_ section, select the storage class to use for objects in your bucket. You can select from four storage classes, or you can select _Autoclass_ and Google adjusts the class as needed.
+
* *Standard* - Best for data that is frequently accessed ("hot" data) or stored for only brief periods of time.
* *Nearline* - A low-cost, highly durable storage service for storing infrequently accessed data.
* *Coldline* - A very-low-cost, highly durable storage service for storing infrequently accessed data.
* *Archive* - The lowest-cost, highly durable storage service for data archiving, online backup, and disaster recovery.
* *Autoclass* - Automatically transitions objects in your bucket to the appropriate storage classes based on each object's access pattern.
+
The cost and retrieval fees are different for each storage class. https://cloud.google.com/storage/docs/storage-classes[See the Google Cloud documentation for more information about storage classes^].

. In the _Protection_ section, choose whether you want to use any data protection tools to protect objects in the bucket, or any data encryption configuration to protect access to your data.
+
*Data protection tools*

* *None* - By default, no protection tools are enabled on the bucket.
* *Object versioning* - Object versioning is a means of keeping multiple versions of an object in the same bucket.
The bucket retains a noncurrent object version each time you update, replace, or delete a live object version - continuously maintaining a protected version of the object. When you select "Object versioning" you can specify two options:
** *Max. number of versions per object* - Enter the number of noncurrent versions per object that will be created.
** *Expire noncurrent versions after* - Enter the number of days after which the older, noncurrent objects will be removed.
* *Retention policy* - A retention policy ensures that all current and future objects in the bucket cannot be deleted or replaced until they reach the age you define in the retention policy. When you select "Retention policy" you can specify two options:
** *Retain objects for* - Enter the number of seconds, days, months, or years that objects will be retained.
** *Time frame* - Select whether the time is in seconds, days, months, or years.
+
The object versioning and retention policy protection tools can't be enabled at the same time. See the Google Cloud documentation for https://cloud.google.com/storage/docs/object-versioning[more information about object versioning^], and https://cloud.google.com/storage/docs/bucket-lock[more information about retention policies^].

+
*Data encryption tools*

* *Google-managed encryption key* - By default, Google-managed encryption keys are used to used to encrypt your data.
* *Customer-managed encryption key* - You can use your own customer-managed keys for data encryption instead of using the default Google-managed encryption keys. If you're planning to use your own customer-managed keys, you'll need to have created them already so you can select the Keys in this page.
+
The keys can be in the same Project as the bucket, or you can select a different Project. 
+
See the Google Cloud documentation for https://cloud.google.com/storage/docs/encryption/default-keys[more information about Google-managed encryption keys^], and https://cloud.google.com/storage/docs/encryption/customer-managed-keys[more information about Customer-managed encryption keys^].

. Click *Add* and the bucket is created.

//.What's next
//
//You can't manually configure Versioning, Tags, or Encryption when initially adding a bucket. After the bucket is created you can configure these other properties of the bucket. link:task-change-gcp-bucket-settings.html[Learn more about changing bucket settings].
